### ISSUE TITLE
Race condition when first generating type definitions

### ISSUE THREAD

**Issue by ecklf** [cometkim/gatsby-plugin-typegen#10]
When `node_modules/types/gatsby.ts` does not exist yet I sometimes run into TypeScript compiler issues because the module has not yet been generated. 

> Error in "/Users/lynx/Projects/blog/gatsby-node.js": ⨯ Unable to compile TypeScript:
> src/lib/createPages.ts:2:41 - error TS2307: Cannot find module 'generated/types/gatsby'.

As far as I know gatsby is running the plugins concurrently, so is there a way to run this plugin manually without `gatsby develop`?

**Comment by cometkim** [comment]
Hey @impulse, Can you share the project configuration?

This plugin only generates "types" and Gatsby strips all types by babel, so even if types is not generated it will not affect your build.

**Comment by ecklf** [comment]
@cometkim I see. I could actually pinpoint my issue in the meanwhile. I use:
```js
require("source-map-support").install()
require("ts-node").register()

exports.createPages = require("./src/lib/createPages").createPages
// ...
```
in my `gatbsy-node.js` so I can write all my Gatsby Actions in TypeScript. The lack of type definitions there cause "cannot find module" errors (createPage to be exact) and will crash the build. I can just check if the generated file exists and block the export on first run as a dirty fix but is there a better solution for this case?

**Comment by cometkim** [comment]
@cometkim I see your issue now. Unfortunately, there is no way to do that :( because gatsby builds the schema at runtime (more specifically the end of plugins and the gatsby-node lifecycle)

I recommends you to use babel with `babel-preset-gatsby-package` and `@babel/preset-typescript` instead of ts-node.

1. It's basically same as `transpileOnly: true`, so you can skip the build error and explicitly checking types with tsc later.
2. Writing any gatsby files with a custom compiler is not safe. because gatsby tries to extract graphql codes statically.

**Comment by ecklf** [comment]
@cometkim sorry I'm late to this. Thanks for the solution, I'll try and report back here if it resolves my issue once I have time to keep working on that side project 👍
