### ISSUE TITLE
Stabilize output

### ISSUE THREAD

**Issue by cometkim** [cometkim/gatsby-plugin-typegen#104]
The plugin artifacts should support stable output to be able to commit without redundant diffs.

Need to either modify the algorithm or prettify the output so order and format will not be changed for the same document.

**Comment by noVerity** [comment]
I tried looking at this, but I've run out of time and need to get back to other things, so I thought I'd just leave some notes.
`gatsby/graphql` offers `lexicographicSortSchema` as an export. Running that in `emitSchema.ts`  seems to update the output correctly (haven't verified) for the main schema which would just leave the plugin documents. 
Unfortunately the package doesn't have the same for the fragments (or I haven't found it) so that would leave it to writing some  sorter anyway or relying on something https://github.com/gajus/format-graphql etc.
Also to note is the difference in the schema between running gatsby with `develop` or `build` since one let's you query for the `host` and `port` values, which can then provide an inconsistent file.

**Comment by cometkim** [comment]
Thanks @noVerity, that's great to know graphql-js has `lexicographicSortSchema` utility. I think documents other than schemas always depend on the user-defined order, so we don't have to touch them.

> Also to note is the difference in the schema between running gatsby with develop or build since one let's you query for the host and port values, which can then provide an inconsistent file.

yep, there is an issue opened for it #103, #131 and I'm working on v3. It will be done easily by using graphql visitor.

**Comment by cometkim** [comment]
This will be fixed in v3. Thanks again @noVerity
