### ISSUE TITLE
new gatsby interface! also .cache/fragments/*.js is being deprecated

### ISSUE THREAD

**Issue by acao** [cometkim/gatsby-plugin-typegen#123]
Hello there!

first off, this plugin is fantastic and in my opinion makes a great candidate for shipping with gatsby much like graphiql/explorer, as we are looking to improve the default typescript experience, if that's something you're interested in.

i wanted to point out two things to you that I came across while working on improved `vscode-graphql` support for gatsby:

1. the new major version no longer has plugins write to `.cache/fragments/*.js` as I understand. many still do this as legacy behavior, however it shouldn't be expected moving forward. 
1. to deal with this, we introduced to the gatsby store a `definitions` `Map` with metadata. it updates as needed with every build, so config changes or plugin development should be able to reflect changes to definitions without restarting the `develop` process
1. an example of this new interface is available here: https://www.npmjs.com/package/gatsby-plugin-graphql-config. this writes all fragments to `.cache/fragments.graphql` with a comment above each with the file URI of the function that generated that fragment. this plugin may be useful if `graphql-codegen` still supports `graphql-config`? I know that it used to. it does this on every change

if you have any interest in and/or opinions about all of this and/or how you may be able to use this feature, let me know! also very curious what other interfaces or helpers for gatsby would make developing a plugin like this easier?

i'm thinking it may be worth exporting a `gatsby-node` API function for this, for example `onChangeGraphQLDefinitions` that fires on startup and every time queries/schema are rebuilt, so that it's easier for us to refactor the store since the direct redux state may not be the most stable API

**Comment by cometkim** [comment]
Thank you for the heads up @acao!

Fortunately, the typegen plugin does not depend on anything on the user's filesystem like `.cache` or `node_modules` since v2 :)

the new `definitions` field and the `onChangeGraphQLDefinitions` idea looks cool! that would definitely make it easier to integrate something with the composed GraphQL schema.

I think a plugin like this should have its own store/scheduler anyway. Watching full schema/documents change is easy, but less efficient that possibly make bad DX in development. So I have to do this now:

```js
const trackedDocuments = new Map();

exports.onPostBootstrap = ({
  store,
  emitter,
}) => {
  emitter.on('SET_GRAPHQL_DEFINITIONS', () => {
    const state = store.getState();

    for (const [key, document] of state.definitions.entries()) {
      const trackedDocument = trackedDocuments.get(key);
      // the `document` is always new instance, but `def` and `text` field inside is only changed on actually changed
      if (trackedDocument !== document.def) {
        console.log(key, document.def);
        trackedDocuments.set(key, document.def);
      }
    }
  });
};
```

If Gatsby provides a lifecycle API let plugins know only changed part (even better if parsed), plugins can access the full schema and document definitions as they need anyway.

**Comment by acao** [comment]
that's what we were hoping to do with `onChangeGraphQLDefinitions`, just trying to see if there is interest in such an API ! thank you
